import type { BarAbsolute, BarDelta, BarGauge, CalculationResult, Diagnostic, EnvironmentSettings, Fraction, Liters, LitersPerMinute, Meters, Seconds } from "../domain/types";
import { barAbsolute, barDelta, barGauge, fraction, liters, litersPerMinute, meters, seconds } from "../domain/units";

/** Inputs and outputs use m, s, bar absolute, and surface liters normalized to 1 bar. */
export type CalculatorResult<T> = CalculationResult<T>;
export const SURFACE_LITER_REFERENCE_PRESSURE_BAR = 1;
export const BEST_MIX_METHOD_ID = "barefoot-best-mix-trimix-v1" as const;
export const END_METHOD_ID = "barefoot-end-narcotic-gas-policy-v1" as const;
export const SAC_METHOD_ID = "barefoot-sac-average-absolute-pressure-v1" as const;
export const EMERGENCY_GAS_METHOD_ID = "barefoot-emergency-gas-schedule-v1" as const;
export const AIR_NITROGEN_FRACTION = 0.79;

type Input = Record<string, unknown>;
const error = (code: string, message: string, field?: string): Diagnostic => ({ code, severity: "error", message, field });
const warning = (code: string, message: string, field?: string): Diagnostic => ({ code, severity: "warning", message, field });
const ok = <T>(value: T, warnings: readonly Diagnostic[] = []): CalculatorResult<T> => ({ ok: true, value, warnings });
const fail = <T>(errors: readonly Diagnostic[]): CalculatorResult<T> => ({ ok: false, errors, warnings: [] });
const finite = (value: unknown, field: string, positive = false): Diagnostic | undefined => typeof value !== "number" || !Number.isFinite(value) || (positive && value <= 0) ? error(positive ? "POSITIVE_REQUIRED" : "FINITE_REQUIRED", `${field} must be ${positive ? "finite and greater than zero" : "finite"}.`, field) : undefined;
const checkFraction = (value: unknown, field: string): Diagnostic[] => { const issue = finite(value, field); const numericValue = value as number; return issue ? [issue] : numericValue < 0 || numericValue > 1 ? [error("FRACTION_RANGE", `${field} must be between 0 and 1.`, field)] : []; };
const ambientPressure = (depthM: Meters, surfacePressureBar: BarAbsolute, metersPerBar: Meters): BarAbsolute => barAbsolute(surfacePressureBar + depthM / metersPerBar);
const commonPressureErrors = (input: Input): Diagnostic[] => {
  const errors: Diagnostic[] = [];
  for (const [key, positive] of [["surfacePressureBar", true], ["metersPerBar", true]] as const) { const issue = finite(input[key], key, positive); if (issue) errors.push(issue); }
  return errors;
};

export type CalculatorEnvironment = Pick<EnvironmentSettings, "surfacePressureBar" | "metersPerBar">;
type EnvironmentInput = { readonly environment?: CalculatorEnvironment; /** @deprecated Pass environment instead. */ readonly surfacePressureBar?: BarAbsolute; /** @deprecated Pass environment instead. */ readonly metersPerBar?: Meters };
function resolveEnvironment(input: EnvironmentInput): { readonly environment?: CalculatorEnvironment; readonly errors: readonly Diagnostic[] } {
  const environment = input.environment ?? (input.surfacePressureBar !== undefined && input.metersPerBar !== undefined ? { surfacePressureBar: input.surfacePressureBar, metersPerBar: input.metersPerBar } : undefined);
  return environment ? { environment, errors: commonPressureErrors(environment as Input) } : { errors: [error("ENVIRONMENT_REQUIRED", "environment with surface pressure and meters per bar is required.", "environment")] };
}

export type ModInput = { oxygen: Fraction; maximumPPO2: BarAbsolute; surfacePressureBar: BarAbsolute; metersPerBar: Meters };
export type ModOutput = { depthM: Meters; ambientPressureBar: BarAbsolute; oxygen: Fraction; maximumPPO2: BarAbsolute };
export function calculateMOD(input: ModInput): CalculatorResult<ModOutput> {
  const errors = [...checkFraction(input.oxygen, "oxygen"), ...commonPressureErrors(input)]; const issue = finite(input.maximumPPO2, "maximumPPO2", true); if (issue) errors.push(issue);
  if (input.oxygen <= 0) errors.push(error("OXYGEN_REQUIRED", "oxygen must be greater than zero.", "oxygen")); if (errors.length) return fail(errors);
  const ambient = input.maximumPPO2 / input.oxygen, depth = (ambient - input.surfacePressureBar) * input.metersPerBar;
  return depth < 0 ? fail([error("MOD_BELOW_SURFACE", "Maximum PPO2 is below the surface PPO2.")]) : ok({ depthM: meters(depth), ambientPressureBar: barAbsolute(ambient), oxygen: input.oxygen, maximumPPO2: input.maximumPPO2 });
}

export type NarcoticGasPolicy = "oxygen-and-nitrogen" | "nitrogen-only";
export type BestMixConstraint = "ppo2" | "end" | "oxygen-fraction";
export type BestMixInput = EnvironmentInput & { readonly depthM: Meters; readonly maximumPPO2: BarAbsolute; readonly maximumENDDepthM?: Meters; readonly narcoticGasPolicy?: NarcoticGasPolicy };
export type BestMixOutput = {
  readonly oxygen: Fraction; readonly nitrogen: Fraction; readonly helium: Fraction; readonly ambientPressureBar: BarAbsolute; readonly actualPPO2Bar: BarAbsolute; readonly achievedENDDepthM: Meters;
  readonly bindingConstraint: BestMixConstraint | "combined"; readonly activeConstraints: readonly BestMixConstraint[]; readonly narcoticGasPolicy: NarcoticGasPolicy; readonly methodId: typeof BEST_MIX_METHOD_ID;
  readonly surfaceBreathability: { readonly breathable: boolean; readonly surfacePPO2Bar: BarAbsolute; readonly minimumPPO2Bar: BarAbsolute; readonly code?: "BEST_MIX_HYPOXIC_AT_SURFACE" };
};
function bestMixConstraints(active: {
  readonly ppo2: boolean;
  readonly end: boolean;
  readonly oxygenFraction: boolean;
}): { readonly bindingConstraint: BestMixOutput["bindingConstraint"]; readonly activeConstraints: readonly BestMixConstraint[] } {
  const activeConstraints: BestMixConstraint[] = [];
  if (active.ppo2) activeConstraints.push("ppo2");
  if (active.end) activeConstraints.push("end");
  if (active.oxygenFraction) activeConstraints.push("oxygen-fraction");
  return {
    bindingConstraint: activeConstraints.length === 1 ? activeConstraints[0] : "combined",
    activeConstraints,
  };
}
export function calculateBestMix(input: BestMixInput): CalculatorResult<BestMixOutput> {
  const resolved = resolveEnvironment(input), errors: Diagnostic[] = [...resolved.errors];
  for (const [field, value, positive] of [["maximumPPO2", input.maximumPPO2, true], ["depthM", input.depthM, false]] as const) { const issue = finite(value, field, positive); if (issue) errors.push(issue); }
  if (input.depthM < 0) errors.push(error("DEPTH_RANGE", "depthM cannot be negative.", "depthM"));
  const maximumENDDepthM = input.maximumENDDepthM ?? input.depthM, endIssue = finite(maximumENDDepthM, "maximumENDDepthM"); if (endIssue) errors.push(endIssue); if (maximumENDDepthM < 0) errors.push(error("END_RANGE", "maximumENDDepthM cannot be negative.", "maximumENDDepthM"));
  if (input.narcoticGasPolicy !== undefined && input.narcoticGasPolicy !== "oxygen-and-nitrogen" && input.narcoticGasPolicy !== "nitrogen-only") errors.push(error("NARCOTIC_POLICY_UNKNOWN", "narcoticGasPolicy must be oxygen-and-nitrogen or nitrogen-only.", "narcoticGasPolicy"));
  if (errors.length || !resolved.environment) return fail(errors);
  const policy = input.narcoticGasPolicy ?? "oxygen-and-nitrogen", target = ambientPressure(input.depthM, resolved.environment.surfacePressureBar, resolved.environment.metersPerBar), endPressure = ambientPressure(maximumENDDepthM, resolved.environment.surfacePressureBar, resolved.environment.metersPerBar), ppo2Limit = input.maximumPPO2 / target;
  let oxygen: number, nitrogen: number, helium: number, constraintMetadata: ReturnType<typeof bestMixConstraints>;
  if (policy === "oxygen-and-nitrogen") {
    const narcoticBudget = Math.min(1, endPressure / target); oxygen = Math.min(1, ppo2Limit, narcoticBudget); helium = Math.max(0, 1 - narcoticBudget); nitrogen = 1 - oxygen - helium;
    constraintMetadata = bestMixConstraints({
      ppo2: ppo2Limit <= 1 && Math.abs(oxygen - ppo2Limit) < 1e-9,
      end: narcoticBudget < 1 - 1e-9,
      oxygenFraction: oxygen >= 1 - 1e-9,
    });
  } else {
    oxygen = Math.min(1, ppo2Limit); nitrogen = Math.min(1 - oxygen, AIR_NITROGEN_FRACTION * endPressure / target); helium = 1 - oxygen - nitrogen;
    const nitrogenEndLimit = AIR_NITROGEN_FRACTION * endPressure / target;
    constraintMetadata = bestMixConstraints({
      ppo2: ppo2Limit <= 1 && Math.abs(oxygen - ppo2Limit) < 1e-9,
      end: nitrogenEndLimit < 1 - oxygen - 1e-9,
      oxygenFraction: oxygen >= 1 - 1e-9,
    });
  }
  nitrogen = Math.max(0, nitrogen); helium = Math.max(0, helium);
  const actualPPO2Bar = barAbsolute(oxygen * target), narcoticFraction = policy === "oxygen-and-nitrogen" ? oxygen + nitrogen : nitrogen, narcoticReferenceFraction = policy === "oxygen-and-nitrogen" ? 1 : AIR_NITROGEN_FRACTION, theoreticalEND = (target * narcoticFraction / narcoticReferenceFraction - resolved.environment.surfacePressureBar) * resolved.environment.metersPerBar;
  const surfacePPO2Bar = barAbsolute(oxygen * resolved.environment.surfacePressureBar), surfaceBreathability = surfacePPO2Bar >= 0.16 ? { breathable: true, surfacePPO2Bar, minimumPPO2Bar: barAbsolute(0.16) } : { breathable: false, surfacePPO2Bar, minimumPPO2Bar: barAbsolute(0.16), code: "BEST_MIX_HYPOXIC_AT_SURFACE" as const };
  const value: BestMixOutput = { oxygen: fraction(oxygen), nitrogen: fraction(nitrogen), helium: fraction(helium), ambientPressureBar: target, actualPPO2Bar, achievedENDDepthM: meters(Math.max(0, theoreticalEND)), ...constraintMetadata, narcoticGasPolicy: policy, methodId: BEST_MIX_METHOD_ID, surfaceBreathability };
  const warnings: Diagnostic[] = [];
  if (ppo2Limit > 1 && oxygen >= 1 - 1e-9) warnings.push({ code: "BEST_MIX_LIMITED_TO_OXYGEN", severity: "info", message: "The requested PPO₂ would require more than 100% oxygen; the result is explicitly limited to oxygen." });
  if (!surfaceBreathability.breathable) warnings.push(warning("BEST_MIX_HYPOXIC_AT_SURFACE", "This maximum-depth mix is hypoxic at the surface; use it only with a qualified travel-gas plan.", "maximumPPO2"));
  return ok(value, warnings);
}

export type EndInput = EnvironmentInput & { readonly depthM: Meters; readonly oxygen: Fraction; readonly helium: Fraction; readonly narcoticGasPolicy?: NarcoticGasPolicy };
export type EndOutput = { readonly endDepthM: Meters; readonly ambientPressureBar: BarAbsolute; readonly narcoticFraction: Fraction; readonly oxygen: Fraction; readonly helium: Fraction; readonly nitrogen: Fraction; readonly narcoticGasPolicy: NarcoticGasPolicy; readonly methodId: typeof END_METHOD_ID };
export function calculateEND(input: EndInput): CalculatorResult<EndOutput> {
  const resolved = resolveEnvironment(input), errors: Diagnostic[] = [...resolved.errors, ...checkFraction(input.helium, "helium"), ...checkFraction(input.oxygen, "oxygen")]; const depthIssue = finite(input.depthM, "depthM"); if (depthIssue) errors.push(depthIssue);
  if (input.depthM < 0) errors.push(error("DEPTH_RANGE", "depthM cannot be negative.", "depthM")); if (input.oxygen + input.helium > 1) errors.push(error("FRACTION_SUM", "oxygen plus helium cannot exceed 1.")); if (input.narcoticGasPolicy !== undefined && input.narcoticGasPolicy !== "oxygen-and-nitrogen" && input.narcoticGasPolicy !== "nitrogen-only") errors.push(error("NARCOTIC_POLICY_UNKNOWN", "narcoticGasPolicy must be oxygen-and-nitrogen or nitrogen-only.", "narcoticGasPolicy"));
  if (errors.length || !resolved.environment) return fail(errors);
  const policy = input.narcoticGasPolicy ?? "oxygen-and-nitrogen", ambient = ambientPressure(input.depthM, resolved.environment.surfacePressureBar, resolved.environment.metersPerBar), nitrogen = 1 - input.oxygen - input.helium, narcotic = policy === "oxygen-and-nitrogen" ? input.oxygen + nitrogen : nitrogen, narcoticReferenceFraction = policy === "oxygen-and-nitrogen" ? 1 : AIR_NITROGEN_FRACTION, theoreticalEnd = (ambient * narcotic / narcoticReferenceFraction - resolved.environment.surfacePressureBar) * resolved.environment.metersPerBar;
  const value: EndOutput = { endDepthM: meters(Math.max(0, theoreticalEnd)), ambientPressureBar: ambient, narcoticFraction: fraction(narcotic), oxygen: input.oxygen, helium: input.helium, nitrogen: fraction(nitrogen), narcoticGasPolicy: policy, methodId: END_METHOD_ID };
  return theoreticalEnd < 0 ? ok(value, [warning("END_LIMITED_TO_SURFACE", "The calculated narcotic pressure is below surface pressure; END is explicitly limited to zero depth.")]) : ok(value);
}

export type GasDensityInput = { oxygen: Fraction; helium: Fraction; ambientPressureBar: BarAbsolute; temperatureC?: number };
export function calculateGasDensity(input: GasDensityInput): CalculatorResult<{ densityKgM3: number; molarMassGmol: number; ambientPressureBar: BarAbsolute }> {
  const errors = [...checkFraction(input.oxygen, "oxygen"), ...checkFraction(input.helium, "helium")], pressureIssue = finite(input.ambientPressureBar, "ambientPressureBar", true); if (pressureIssue) errors.push(pressureIssue); if (input.oxygen + input.helium > 1) errors.push(error("FRACTION_SUM", "oxygen plus helium cannot exceed 1.")); if (input.temperatureC !== undefined) { const issue = finite(input.temperatureC, "temperatureC"); if (issue) errors.push(issue); } const temperatureK = (input.temperatureC ?? 20) + 273.15; if (temperatureK <= 0) errors.push(error("TEMPERATURE_INVALID", "Absolute temperature must be positive.", "temperatureC")); if (errors.length) return fail(errors); const nitrogen = 1 - input.oxygen - input.helium, molarMass = input.oxygen * 31.998 + input.helium * 4.0026 + nitrogen * 28.0134; return ok({ densityKgM3: input.ambientPressureBar * 100000 * (molarMass / 1000) / (8.314462618 * temperatureK), molarMassGmol: molarMass, ambientPressureBar: input.ambientPressureBar });
}
export function calculatePPO2(input: { oxygen: Fraction; ambientPressureBar: BarAbsolute }): CalculatorResult<{ ppo2Bar: BarAbsolute; oxygen: Fraction; ambientPressureBar: BarAbsolute }> { const errors = [...checkFraction(input.oxygen, "oxygen")], issue = finite(input.ambientPressureBar, "ambientPressureBar", true); if (issue) errors.push(issue); return errors.length ? fail(errors) : ok({ ppo2Bar: barAbsolute(input.oxygen * input.ambientPressureBar), oxygen: input.oxygen, ambientPressureBar: input.ambientPressureBar }); }

export type GasUseLeg = { startDepthM: Meters; endDepthM: Meters; durationSeconds: Seconds; rmvLpm: LitersPerMinute; teamSize?: number };
export function integratedSurfaceGas(leg: GasUseLeg, surfacePressureBar: BarAbsolute, metersPerBar: Meters): number { return leg.durationSeconds / 60 * leg.rmvLpm * (surfacePressureBar + (leg.startDepthM + leg.endDepthM) / 2 / metersPerBar) / SURFACE_LITER_REFERENCE_PRESSURE_BAR * (leg.teamSize ?? 1); }
function validateLegs(legs: readonly GasUseLeg[], environment: CalculatorEnvironment): Diagnostic[] { const errors = [...commonPressureErrors(environment as Input)]; legs.forEach((leg, index) => { for (const [field, value] of [["startDepthM", leg.startDepthM], ["endDepthM", leg.endDepthM]] as const) { const issue = finite(value, `legs.${index}.${field}`); if (issue) errors.push(issue); else if (value < 0) errors.push(error("DEPTH_RANGE", "Depth cannot be negative.", `legs.${index}.${field}`)); } for (const [field, value] of [["durationSeconds", leg.durationSeconds], ["rmvLpm", leg.rmvLpm]] as const) { const issue = finite(value, `legs.${index}.${field}`, true); if (issue) errors.push(issue); } if (leg.teamSize !== undefined && (!Number.isInteger(leg.teamSize) || leg.teamSize < 1)) errors.push(error("TEAM_SIZE_INVALID", "teamSize must be a positive integer.", `legs.${index}.teamSize`)); }); return errors; }

export type SacInput = EnvironmentInput & { readonly durationSeconds: Seconds; readonly startDepthM: Meters; readonly endDepthM: Meters } & ({ readonly kind: "surface-volume"; readonly gasUsedL: Liters } | { readonly kind: "cylinder-pressure-drop"; readonly cylinderWaterVolumeL: Liters; readonly startingPressureBar: BarGauge; readonly endingPressureBar: BarGauge } | /** @deprecated Legacy direct surface-volume shape. */ { readonly kind?: undefined; readonly gasUsedL: Liters });
export type SacOutput = { readonly sacLpm: LitersPerMinute; readonly averageAmbientPressureBar: BarAbsolute; readonly gasUsedL: Liters; readonly methodId: typeof SAC_METHOD_ID; readonly source: "surface-volume" | "cylinder-pressure-drop" };
export function calculateSAC(input: SacInput): CalculatorResult<SacOutput> {
  const resolved = resolveEnvironment(input), errors: Diagnostic[] = [...resolved.errors], durationIssue = finite(input.durationSeconds, "durationSeconds", true); if (durationIssue) errors.push(durationIssue); for (const [field, value] of [["startDepthM", input.startDepthM], ["endDepthM", input.endDepthM]] as const) { const issue = finite(value, field); if (issue) errors.push(issue); else if (value < 0) errors.push(error("DEPTH_RANGE", `${field} cannot be negative.`, field)); }
  let gasUsed: Liters | undefined, source: SacOutput["source"] = "surface-volume";
  if (input.kind === "cylinder-pressure-drop") { source = "cylinder-pressure-drop"; for (const [field, value] of [["cylinderWaterVolumeL", input.cylinderWaterVolumeL], ["startingPressureBar", input.startingPressureBar], ["endingPressureBar", input.endingPressureBar]] as const) { const issue = finite(value, field, field === "cylinderWaterVolumeL" || field === "startingPressureBar"); if (issue) errors.push(issue); } if (input.endingPressureBar < 0) errors.push(error("SAC_ENDING_PRESSURE_NEGATIVE", "endingPressureBar cannot be negative.", "endingPressureBar")); if (input.endingPressureBar >= input.startingPressureBar) errors.push(error("SAC_PRESSURE_DROP_REQUIRED", "endingPressureBar must be lower than startingPressureBar.", "endingPressureBar")); gasUsed = liters(input.cylinderWaterVolumeL * (input.startingPressureBar - input.endingPressureBar)); } else { const issue = finite(input.gasUsedL, "gasUsedL", true); if (issue) errors.push(issue); else gasUsed = input.gasUsedL; }
  if (errors.length || !resolved.environment || gasUsed === undefined) return fail(errors); const averageAmbientPressureBar = barAbsolute((ambientPressure(input.startDepthM, resolved.environment.surfacePressureBar, resolved.environment.metersPerBar) + ambientPressure(input.endDepthM, resolved.environment.surfacePressureBar, resolved.environment.metersPerBar)) / 2); return ok({ sacLpm: litersPerMinute(gasUsed / (input.durationSeconds / 60) / averageAmbientPressureBar), averageAmbientPressureBar, gasUsedL: gasUsed, methodId: SAC_METHOD_ID, source });
}
export const calculateRMV = calculateSAC;

export function calculateGasDuration(input: { cylinderWaterVolumeL: Liters; startingPressureBar: BarGauge; reservePressureBar: BarGauge; rmvLpm: LitersPerMinute; ambientPressureBar: BarAbsolute }): CalculatorResult<{ durationSeconds: Seconds; usableGasL: Liters }> { const errors: Diagnostic[] = []; for (const [key, value] of Object.entries(input)) { const issue = finite(value, key, key !== "reservePressureBar"); if (issue) errors.push(issue); } if (input.reservePressureBar < 0) errors.push(error("RESERVE_NEGATIVE", "Reserve pressure cannot be negative.", "reservePressureBar")); if (input.reservePressureBar > input.startingPressureBar) errors.push(error("RESERVE_EXCEEDS_START", "Reserve pressure cannot exceed starting pressure.")); if (errors.length) return fail(errors); const usable = input.cylinderWaterVolumeL * (input.startingPressureBar - input.reservePressureBar); return ok({ durationSeconds: seconds(usable / (input.rmvLpm * input.ambientPressureBar) * 60), usableGasL: liters(usable) }); }
export function calculateCylinderGas(input: { waterVolumeL: Liters; pressureBar: BarGauge; reservePressureBar?: BarGauge }): CalculatorResult<{ totalGasL: Liters; usableGasL: Liters; reserveGasL: Liters }> { const errors: Diagnostic[] = []; for (const [key, value] of Object.entries(input)) if (value !== undefined) { const issue = finite(value, key, key !== "reservePressureBar"); if (issue) errors.push(issue); } if (input.reservePressureBar !== undefined && input.reservePressureBar < 0) errors.push(error("RESERVE_NEGATIVE", "Reserve pressure cannot be negative.", "reservePressureBar")); if (input.reservePressureBar !== undefined && input.reservePressureBar > input.pressureBar) errors.push(error("RESERVE_EXCEEDS_PRESSURE", "Reserve pressure cannot exceed cylinder pressure.")); if (errors.length) return fail(errors); const reserve = (input.reservePressureBar ?? barGauge(0)) * input.waterVolumeL; return ok({ totalGasL: liters(input.waterVolumeL * input.pressureBar), usableGasL: liters(input.waterVolumeL * input.pressureBar - reserve), reserveGasL: liters(reserve) }); }

export type EmergencyGasSegment = { readonly kind: "ascent" | "stop"; readonly startDepthM: Meters; readonly endDepthM: Meters; readonly durationSeconds: Seconds; readonly rmvLpm: LitersPerMinute };
export type EmergencyGasCylinderContext = { readonly waterVolumeL: Liters; readonly startingPressureBar: BarGauge; readonly reservePressureBar: BarGauge };
type EmergencyGasBaseInput = EnvironmentInput & { readonly failureDepthM: Meters; readonly segments: readonly EmergencyGasSegment[] };
export type EmergencyGasInput = EmergencyGasBaseInput & (
  | { readonly mode: "oc"; readonly teamSize: number; readonly cylinder?: EmergencyGasCylinderContext }
  | { readonly mode: "ccr"; readonly teamSize?: 1; readonly cylinder: EmergencyGasCylinderContext }
);
export type EmergencyGasOutput = { readonly requiredGasL: Liters; readonly teamMultiplier: number; readonly segments: readonly { readonly gasUsedL: Liters; readonly averageAmbientPressureBar: BarAbsolute }[]; readonly methodId: typeof EMERGENCY_GAS_METHOD_ID; readonly pressureDropBar?: BarDelta; readonly requiredStartingPressureBar?: BarGauge; readonly remainingPressureBar?: BarGauge; readonly availablePressureBar?: BarDelta; readonly marginPressureBar?: BarDelta; readonly availableGasL?: Liters; readonly marginGasL?: Liters; readonly sufficient?: boolean };
export function calculateEmergencyGas(input: EmergencyGasInput): CalculatorResult<EmergencyGasOutput> {
  const resolved = resolveEnvironment(input), errors: Diagnostic[] = [...resolved.errors], schedule = Array.isArray(input.segments) ? input.segments : [], failureDepthIssue = finite(input.failureDepthM, "failureDepthM"); if (failureDepthIssue) errors.push(failureDepthIssue); else if (input.failureDepthM < 0) errors.push(error("DEPTH_RANGE", "failureDepthM cannot be negative.", "failureDepthM")); if (schedule.length === 0) errors.push(error("EMERGENCY_SCHEDULE_REQUIRED", "At least one ascent or stop segment is required.", "segments")); if (input.mode !== "oc" && input.mode !== "ccr") errors.push(error("EMERGENCY_MODE_INVALID", "mode must be oc or ccr.", "mode")); if (input.mode === "oc" && input.teamSize === undefined) errors.push(error("OC_TEAM_SIZE_REQUIRED", "OC emergency gas requires an explicit teamSize.", "teamSize")); else if (input.mode === "ccr" && input.teamSize !== undefined && input.teamSize !== 1) errors.push(error("CCR_TEAM_SIZE_FIXED", "CCR emergency gas always uses a team multiplier of 1.", "teamSize")); else if (input.teamSize !== undefined && (!Number.isInteger(input.teamSize) || input.teamSize < 1)) errors.push(error("TEAM_SIZE_INVALID", "teamSize must be a positive integer.", "teamSize")); if (input.mode === "ccr" && !input.cylinder) errors.push(error("CCR_BAILOUT_CYLINDER_REQUIRED", "CCR simplified bailout requires one cylinder context.", "cylinder"));
  schedule.forEach((segment, index) => { if (segment.kind !== "ascent" && segment.kind !== "stop") errors.push(error("EMERGENCY_SEGMENT_KIND", "Segment kind must be ascent or stop.", `segments.${index}.kind`)); for (const [field, value] of [["startDepthM", segment.startDepthM], ["endDepthM", segment.endDepthM]] as const) { const issue = finite(value, `segments.${index}.${field}`); if (issue) errors.push(issue); else if (value < 0) errors.push(error("DEPTH_RANGE", "Depth cannot be negative.", `segments.${index}.${field}`)); } for (const [field, value] of [["durationSeconds", segment.durationSeconds], ["rmvLpm", segment.rmvLpm]] as const) { const issue = finite(value, `segments.${index}.${field}`, true); if (issue) errors.push(issue); } if (segment.kind === "ascent" && segment.endDepthM >= segment.startDepthM) errors.push(error("EMERGENCY_ASCENT_NOT_SHALLOWER", "An ascent segment must end shallower than it starts.", `segments.${index}`)); if (segment.kind === "stop" && Math.abs(segment.startDepthM - segment.endDepthM) > 1e-9) errors.push(error("EMERGENCY_STOP_DEPTH_CHANGED", "A stop segment must start and end at the same depth.", `segments.${index}`)); if (index === 0 && Math.abs(segment.startDepthM - input.failureDepthM) > 1e-9) errors.push(error("EMERGENCY_FAILURE_DEPTH_MISMATCH", "The first emergency segment must start at failureDepthM.", `segments.${index}.startDepthM`)); if (index === schedule.length - 1 && Math.abs(segment.endDepthM) > 1e-9) errors.push(error("EMERGENCY_SCHEDULE_NOT_SURFACE", "The final emergency segment must end at the surface.", `segments.${index}.endDepthM`)); if (index > 0 && Math.abs(schedule[index - 1].endDepthM - segment.startDepthM) > 1e-9) errors.push(error("EMERGENCY_SCHEDULE_GAP", "Emergency schedule segments must be contiguous and ordered.", `segments.${index}.startDepthM`)); });
  if (input.cylinder) { for (const [field, value] of [["waterVolumeL", input.cylinder.waterVolumeL], ["startingPressureBar", input.cylinder.startingPressureBar]] as const) { const issue = finite(value, `cylinder.${field}`, true); if (issue) errors.push(issue); } const reserveIssue = finite(input.cylinder.reservePressureBar, "cylinder.reservePressureBar"); if (reserveIssue) errors.push(reserveIssue); else if (input.cylinder.reservePressureBar < 0) errors.push(error("RESERVE_NEGATIVE", "reservePressureBar cannot be negative.", "cylinder.reservePressureBar")); else if (input.cylinder.reservePressureBar > input.cylinder.startingPressureBar) errors.push(error("RESERVE_EXCEEDS_START", "reservePressureBar cannot exceed startingPressureBar.", "cylinder.reservePressureBar")); }
  if (errors.length || !resolved.environment) return fail(errors); const teamMultiplier = input.mode === "ccr" ? 1 : input.teamSize, segments = schedule.map((segment) => { const averageAmbientPressureBar = barAbsolute((ambientPressure(segment.startDepthM, resolved.environment!.surfacePressureBar, resolved.environment!.metersPerBar) + ambientPressure(segment.endDepthM, resolved.environment!.surfacePressureBar, resolved.environment!.metersPerBar)) / 2); return { gasUsedL: liters(integratedSurfaceGas({ ...segment, teamSize: teamMultiplier }, resolved.environment!.surfacePressureBar, resolved.environment!.metersPerBar)), averageAmbientPressureBar }; }), requiredGasL = liters(segments.reduce((sum, segment) => sum + segment.gasUsedL, 0));
  if (!input.cylinder) return ok({ requiredGasL, teamMultiplier, segments, methodId: EMERGENCY_GAS_METHOD_ID }); const reservePressureBar = input.cylinder.reservePressureBar, pressureDropBar = barDelta(requiredGasL / input.cylinder.waterVolumeL), requiredStartingPressureBar = barGauge(reservePressureBar + pressureDropBar), projectedRemaining = input.cylinder.startingPressureBar - pressureDropBar, remainingPressureBar = barGauge(Math.max(0, projectedRemaining)), availablePressureBar = barDelta(input.cylinder.startingPressureBar - reservePressureBar), marginPressureBar = barDelta(availablePressureBar - pressureDropBar), availableGasL = liters(input.cylinder.waterVolumeL * availablePressureBar), marginGasL = liters(availableGasL - requiredGasL), sufficient = marginPressureBar >= 0; return ok({ requiredGasL, teamMultiplier, segments, methodId: EMERGENCY_GAS_METHOD_ID, pressureDropBar, requiredStartingPressureBar, remainingPressureBar, availablePressureBar, marginPressureBar, availableGasL, marginGasL, sufficient }, sufficient ? [] : [warning("EMERGENCY_GAS_INSUFFICIENT", "The selected cylinder does not retain the entered reserve after the emergency schedule.", "cylinder.startingPressureBar")]);
}

/** Compatibility wrapper for historical rock-bottom callers. */
export function calculateRockBottom(input: { legs: readonly GasUseLeg[]; surfacePressureBar: BarAbsolute; metersPerBar: Meters; cylinderWaterVolumeL?: Liters }): CalculatorResult<{ requiredGasL: Liters; minimumPressureBar?: BarDelta; legs: readonly { gasUsedL: Liters }[] }> { const errors = validateLegs(input.legs, { surfacePressureBar: input.surfacePressureBar, metersPerBar: input.metersPerBar }); if (input.cylinderWaterVolumeL !== undefined) { const issue = finite(input.cylinderWaterVolumeL, "cylinderWaterVolumeL", true); if (issue) errors.push(issue); } if (errors.length) return fail(errors); const values = input.legs.map((leg) => integratedSurfaceGas(leg, input.surfacePressureBar, input.metersPerBar)), total = values.reduce((sum, value) => sum + value, 0); return ok({ requiredGasL: liters(total), minimumPressureBar: input.cylinderWaterVolumeL === undefined ? undefined : barDelta(total / input.cylinderWaterVolumeL), legs: values.map((gasUsedL) => ({ gasUsedL: liters(gasUsedL) })) }); }

/** NOAA single-exposure table. Source values are minutes; interpolation is a Barefoot policy. */
const NOAA_LIMITS_MINUTES = Object.freeze([[0.6, 720], [0.7, 570], [0.8, 450], [0.9, 360], [1.0, 300], [1.1, 240], [1.2, 210], [1.3, 180], [1.4, 150], [1.5, 120], [1.6, 45]] as const);
export function calculateCNS(input: { ppo2Bar: BarAbsolute; durationSeconds: Seconds }): CalculatorResult<{ percent: number; limitSeconds: number; method: "NOAA-table-Barefoot-linear-interpolation-v1"; ppo2Bar: BarAbsolute }> { const errors: Diagnostic[] = []; for (const [field, value] of Object.entries(input)) { const issue = finite(value, field, true); if (issue) errors.push(issue); } if (errors.length) return fail(errors); if (input.ppo2Bar < 0.6) return fail([error("PPO2_BELOW_NOAA_TABLE", "PPO2 below 0.6 bar is outside the cited NOAA single-exposure table.", "ppo2Bar")]); if (input.ppo2Bar > 1.6) return fail([error("PPO2_EXCEEDS_NOAA_TABLE", "PPO2 above 1.6 bar is outside the cited NOAA single-exposure table.", "ppo2Bar")]); let limitMinutes: number = NOAA_LIMITS_MINUTES[0][1]; if (input.ppo2Bar >= NOAA_LIMITS_MINUTES.at(-1)![0]) limitMinutes = NOAA_LIMITS_MINUTES.at(-1)![1]; else for (let index = 0; index < NOAA_LIMITS_MINUTES.length - 1; index += 1) { const [lowerPPO2, lowerLimit] = NOAA_LIMITS_MINUTES[index], [upperPPO2, upperLimit] = NOAA_LIMITS_MINUTES[index + 1]; if (input.ppo2Bar >= lowerPPO2 && input.ppo2Bar <= upperPPO2) { limitMinutes = lowerLimit + (input.ppo2Bar - lowerPPO2) / (upperPPO2 - lowerPPO2) * (upperLimit - lowerLimit); break; } } const limitSeconds = limitMinutes * 60; return ok({ percent: input.durationSeconds / limitSeconds * 100, limitSeconds, method: "NOAA-table-Barefoot-linear-interpolation-v1", ppo2Bar: input.ppo2Bar }); }
/** Compatibility wrapper for simplified bailout callers. */
export function calculateSimplifiedBailout(input: { legs: readonly GasUseLeg[]; surfacePressureBar: BarAbsolute; metersPerBar: Meters; cylinderWaterVolumeL?: Liters }): CalculatorResult<{ requiredGasL: Liters; minimumPressureBar?: BarDelta }> { const result = calculateRockBottom(input); return result.ok ? ok({ requiredGasL: result.value.requiredGasL, minimumPressureBar: result.value.minimumPressureBar }) : result; }

export const MOD = calculateMOD; export const bestMix = calculateBestMix; export const END = calculateEND; export const gasDensity = calculateGasDensity; export const PPO2 = calculatePPO2; export const SAC = calculateSAC; export const gasDuration = calculateGasDuration; export const rockBottom = calculateRockBottom; export const emergencyGas = calculateEmergencyGas; export const cylinderGas = calculateCylinderGas; export const CNS = calculateCNS; export const simplifiedBailout = calculateSimplifiedBailout;
